// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2hWT4ynddin-tPFXxIZgZC1VgEdcdDs',
    appId: '1:425870704902:web:facdaad47c16c3cd421e87',
    messagingSenderId: '425870704902',
    projectId: 'eryaz-1',
    authDomain: 'eryaz-1.firebaseapp.com',
    storageBucket: 'eryaz-1.appspot.com',
    measurementId: 'G-423QFP2KNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbxumoIbphpFyTs4hjgUR5KP6CUxNRyAQ',
    appId: '1:425870704902:android:5116ff3f28294c7b421e87',
    messagingSenderId: '425870704902',
    projectId: 'eryaz-1',
    storageBucket: 'eryaz-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc51TQsyckj__cAM7vChSZHgADk3aBNxA',
    appId: '1:425870704902:ios:a3dd763db7a7cf0a421e87',
    messagingSenderId: '425870704902',
    projectId: 'eryaz-1',
    storageBucket: 'eryaz-1.appspot.com',
    iosBundleId: 'com.example.eryaz2',
  );

}